---
name: "release"

on:
    push:
        branches:
            - "phase-2"

jobs:
    release:
        name: "Project Release"
        runs-on: "ubuntu-latest"

        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: "Compress and Release"
              run: |
                  echo "Compressing files..."
                  zip phase-2 *.html *.js *.css
            - uses: "marvinpinto/action-automatic-releases@latest"
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  automatic_release_tag: "phase-2"
                  prerelease: false
                  title: "Phase 2"
                  files: |
                      phase-2.zip
            - run: |
                  echo "Files have been successfully compressed."
