---
name: "release-latest"

on:
    push:
        branches:
            - "main"

jobs:
    release:
        name: "Project Release"
        runs-on: "ubuntu-latest"

        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: "Compress and Release"
              run: |
                  echo "Compressing files..."
                  zip -r project *.html assets server tally.* CREDITS.md LICENSE README.md
            - uses: "marvinpinto/action-automatic-releases@latest"
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  automatic_release_tag: "latest"
                  prerelease: false
                  title: "Project Release"
                  files: |
                      project.zip
            - run: |
                  echo "Files have been successfully compressed."
